### ISSUE TITLE
webscoket监听和发送不能同时存在，每次都是新建？

### ISSUE THREAD

**Issue by Alexxiaopang** [ysbing/Glint#1]

**Comment by ysbing** [comment]
如果使用的连接是相同的，它们是共享的，GlintSocketServiceStub#mSocketArray对象是它们的共享池

**Comment by Alexxiaopang** [comment]
cmdid有什么用？

**Comment by ysbing** [comment]
因为socket回调事件很多，cmdid是用来过滤这些事件的，具体可以看GlintSocketCore#messagePush()方法

**Comment by Alexxiaopang** [comment]
谢谢回复
