### ISSUE TITLE
wss连接不上，用的是官方给的链接

### ISSUE THREAD

**Issue by Alexxiaopang** [ysbing/Glint#2]
如题，ws://echo.websocket.org   这个是官方给的demo链接，链接和发送不成功

**Comment by ysbing** [comment]
待我调试后告诉你原因

**Comment by ysbing** [comment]
已知道原因，是解析socket数据出了问题，或许可以考虑将解析业务数据丢到上层去实现，感谢你的反馈，我会在这几天实现并完成测试

**Comment by Alexxiaopang** [comment]
感谢回复，感谢提供那么好用的库，不过也提一个建议，建议把OKHTTP做成可选依赖，因为主项目肯定会集成OK

**Comment by ysbing** [comment]
做成可选依赖会有隐患，可能有些项目没依赖OKHTTP会找不到类而崩溃，可以尽可能的将依赖的版本低一点，这样依赖合并后大概率是使用项目的版本号

**Comment by Alexxiaopang** [comment]
看了一下websocket这块，有两个疑问：可以解惑一下么
1.我看了一下，这里面并没有涉及重连和心跳机制，请问支持重连和心跳？
2.同一链接，设置监听和发送都存在着回调事件，那时候后设置的会覆盖前面的？还是两个回调同时执行？
如果先设置监听，但是发送直接是调用execute（）；会发生什么
（没办法调试代码，wss链接不成功，无法实验）

**Comment by ysbing** [comment]
第一个问题的回答：重连属于业务行为，故没有在底层实现，在业务层的实现需要根据业务服务端的返回内容来判断是否要重连；
心跳机制是有的，在GlintSocketCore的143行，发送2::保持心跳

**Comment by ysbing** [comment]
第二个问题的回答：设置监听和发送都有回调事件，会两个回调同时执行

**Comment by ysbing** [comment]
如果先设置监听，但是发送直接是调用execute（），也是没问题的，会在执行成功后回调之前做的监听，所以当你离开应用时，要调用off方法来关闭这些监听

**Comment by Alexxiaopang** [comment]
重连机制的话因为不知道这个链接是否还活着，断网这些都还好监测，但是中途突然断开了，要执行重连就难了

**Comment by ysbing** [comment]
每次调用都会做一次重连的GlintSocketServiceStub.connect()，中途突然断开可以不用理会，有做了自动处理，我上面所说的是鉴权失败导致的重连，就需要通过服务端的返回来判断了。

**Comment by ysbing** [comment]
@Alexxiaopang 新特性代码已提交，对Socket的业务数据做了处理，可自定义解析数据，详情可看例子
